services:
    app:
        image: sylius/standard:1.11-traditional-alpine
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
            # DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Rome"
            PHP_VERSION: "8.1"
        volumes:
            - ./:/app:delegated
            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 8080:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        volumes:
            - mysql-data:/var/lib/mysql:rw
        networks:
            - sylius
    
    elasticsearch:
        build:
            context: ./.docker/elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "xpack.security.enabled=false"
        volumes:
            - es-data:/usr/share/elasticsearch/data:rw
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - sylius

    elastichq:
        image: elastichq/elasticsearch-hq
        networks:
            - sylius

networks:
    sylius:
        driver: bridge

volumes:
    mysql-data:
    es-data:
