services:
    app:
        profiles: ["disabled"]

    mysql:
        command: --max_allowed_packet=1073741824
        ports:
            - "13306:3306"

    elasticsearch:
        ports:
            - "9200:9200"
            - "9300:9300"

    elastichq:
        environment:
            - HQ_DEFAULT_URL=http://elasticsearch:9200
        ports:
            - "5000:5000"

    #For development only
    mailhog:
        image: mailhog/mailhog
        labels:
            com.symfony.server.service-prefix: 'MAILER'
        ports:
            - "11025:1025"
            - "18025:8025"
