# Delete these routes and define your own shop routes here

sylius_shop_product_index:
    path: /taxons/{slug}
    methods: [GET]
    defaults:
        _controller: lruozzi9.sylius_elasticsearch_plugin.controller.elasticsearch::taxonAction
    requirements:
        slug: .+(?<!/)
