# Delete these routes and define your own shop routes here

sylius_shop_product_index:
    path: /taxons/{slug}
    methods: [GET]
    defaults:
        _controller: webgriffe.sylius_elasticsearch_plugin.controller.elasticsearch::taxonAction
    requirements:
        slug: .+(?<!/)

sylius_shop_search:
    path: /search/{query}
    methods: [GET, POST]
    defaults:
        _controller: webgriffe.sylius_elasticsearch_plugin.controller.elasticsearch::searchAction
        query: null
    requirements:
        query: .+(?<!/)

sylius_shop_instant_search:
    path: /instant-search/{query}
    methods: [GET]
    defaults:
        _controller: webgriffe.sylius_elasticsearch_plugin.controller.elasticsearch::instantSearchAction
    requirements:
        query: .+(?<!/)
